Server:
  GrpcPort: 8081
  HttpPort: 8082
  ServiceName: "shopping"
App:
  DefaultPageSize: 10
  MaxPageSize: 100
  DefaultContextTimeout: 60
  LogSavePath: ./storage/logs/
  LogFileName: app
  LogFileExt: .log
Database:
  DBType: mysql
  UserName: root        # 填写你的数据库账号
  Password: 123456      # 填写你的数据库密码
  Host: 127.0.0.1:3306
  DBName: charites      # 填写你的数据库名称
  TablePrefix: shopping_
  Charset: utf8mb4
  ParseTime: True
  MaxIdleConns: 10
  MaxOpenConns: 30
Redis:
  Address: localhost:6379
  Password: ""
  DB: 0
  PoolSize: 20
Consul:
  Address: 127.0.0.1:8500

